defaults: &defaults
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: scrumboard
  password:

development:
  <<: *defaults
  database: scrumboard_development

test:
  <<: *defaults
  database: scrumboard_test

production:
  <<: *defaults
  database: scrumboard_production